[build]
  # Build command that generates Prisma client and creates production build
  command = "npm run build"
  
  # Netlify Functions directory
  functions = "netlify/functions"
  
  # Publish directory
  publish = "."

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Ensure production environment
  NODE_ENV = "production"